In [29]:
import pandas as pd
import numpy as np
import os
import json
import ast
from collections import Counter
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Participants Information

Out of valid submissions - 32 were removed due to word limit violation

## Stage 1

In [20]:
base_path = "../data/stage1/"
directories = [d for d in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, d))]
directories

['data_0109',
 'data_2208',
 'data_2208_2',
 'data_2208_3',
 'data_2208_4',
 'data_2308',
 'data_2408_2',
 'data_2408_3',
 'data_2408_5',
 'data_2408_6',
 'data_3108',
 'data_main_2',
 'data_main_3',
 'data_writing_main_en']

In [47]:
all_data = []

# Iterate over each directory
for directory in directories:
    # Construct the path to participant_info.json
    file_path = os.path.join(base_path, directory, 'participant_info.json')
    
    # Check if the file exists
    if os.path.exists(file_path):
        # Open and read the json file
        with open(file_path, 'r') as file:
            for line in file:
                # Parse each line as JSON and append to the list
                all_data.append(json.loads(line))

# Convert the list of JSON objects into a DataFrame
participant_info = pd.DataFrame(all_data)

In [48]:
participant_info = participant_info[participant_info['prolific_id']!="65e6fb8c62b34b6ef5249890"]
participant_info['timestamp'] = participant_info['timestamp'].apply(lambda x: x['$date'])
participant_info['timestamp'] = pd.to_datetime(participant_info['timestamp'])
participant_info['_id'] = participant_info['_id'].apply(lambda x: x['$oid'])
participant_info = participant_info.drop_duplicates()
participant_info.head(1)

,_id,prolific_id,study_id,age,gender,english_proficiency,spanish_proficiency,timestamp
0,66c919a3b087a0712a44d22a,66b5033d08cabdd45450af9d,66c63f4f7c3e886b7c9cc498,21,male,native,intermediate,2024-08-23 22:22:37.119000+00:00

In [49]:
final_document_list = pd.read_csv('../data/buckets_combined/master_documents_with_pid.csv')
final_document_list.head(1)

,_id,content,name,chunks,timestamp,task_id,prolific_id,study_id,plain_text,word_count,TASK_ID
0,66c5a13c86c57a87db6f59d9,"<p class=""llmparagraph id0""><span id=""chunk_TD...",NaN,"[{'frontend_id': 'chunk_JfRRo', 'versions': [{...",2024-08-21 08:11:40.473000+00:00,main_task_1,5a4ff22bacc75b000179b0e9,66c516b1d61c7b572205f713,Join hands with us in protecting our planet's ...,193,ENG

In [50]:
participant_info['prolific_id'] = participant_info['prolific_id'].str.replace('ABCDEF', '66617548416d40fa86a254a0')

In [51]:
final_partifipant_list = participant_info[participant_info['prolific_id'].isin(final_document_list['prolific_id'].tolist())].drop_duplicates(subset='prolific_id')
final_partifipant_list

,_id,prolific_id,study_id,age,gender,english_proficiency,spanish_proficiency,timestamp
2,66c94b29b087a0712a44d22e,6672e1f88167a9b1cdde969a,66c63f4f7c3e886b7c9cc498,36,female,native,intermediate,2024-08-23 22:22:37.119000+00:00
11,66c9d5e7925382be5771897f,66829fd32d471e7ca06e92df,66c90fcc4541f87369be0127,48,male,native,,2024-08-24 12:40:14.128000+00:00
12,66c9d5ff925382be57718980,638070625c26e262f2163254,66c90fcc4541f87369be0127,64,male,native,,2024-08-24 12:40:14.128000+00:00
14,66c9d830925382be57718986,66c97c855434e33b086cc53b,66c90fcc4541f87369be0127,34,female,native,,2024-08-24 12:40:14.128000+00:00
15,66c9d861925382be57718987,6669f862528d0daadf3d2fe6,66c90fcc4541f87369be0127,47,male,native,,2024-08-24 12:40:14.128000+00:00
...,...,...,...,...,...,...,...,...
435,66c5a18086c57a87db6f59dc,5f22932ca6ff8f000918fdfb,66c516b1d61c7b572205f713,33,female,,beginner,2024-08-21 08:04:34.644000+00:00
436,66c5a1cd86c57a87db6f59dd,5ea9a41b87b4150bf9634637,66c516b1d61c7b572205f713,21,female,,intermediate,2024-08-21 08:04:34.644000+00:00
450,66c5a7ac86c57a87db6f5a17,60a0b744298c64d46b63e893,66c516b1d61c7b572205f713,59,female,,beginner,2024-08-21 08:04:34.644000+00:00
516,66c5e3652f44d7b54f76e528,5c068f1f9d0df40001e5688c,66c516b1d61c7b572205f713,33,female,native,,2024-08-21 12:48:03.576000+00:00
517,66c5e49d2f44d7b54f76e52c,60c0c4333e49151d768bb35b,66c516b1d61c7b572205f713,71,female,native,,2024-08-21 12:48:03.576000+00:00

In [53]:
final_partifipant_list.shape

(64, 8)

In [54]:
final_document_list.shape

(96, 11)

In [52]:
final_partifipant_list['age'].describe()

count    64.000000
mean     34.562500
std      13.507053
min       6.000000
25%      26.000000
50%      33.000000
75%      43.000000
max      71.000000
Name: age, dtype: float64

In [31]:
final_partifipant_list['gender'].value_counts()

gender
female        37
male          26
non-binary     1
Name: count, dtype: int64

In [32]:
final_partifipant_list['english_proficiency'].value_counts()

english_proficiency
native          36
advanced        15
                10
intermediate     3
Name: count, dtype: int64

In [33]:
final_partifipant_list['spanish_proficiency'].value_counts()

spanish_proficiency
native          26
                22
advanced         7
intermediate     6
beginner         3
Name: count, dtype: int64

In [56]:
final_partifipant_list.shape

(64, 8)

In [57]:
final_partifipant_list.to_csv('../output/paper_output/stage1_participant.csv',index=False)

## Stage 2

In [64]:
donation_survey_data_t = pd.read_csv('../output/final_collected_survey.csv')
donation_survey_data_t.head(1)

,PROLIFIC_PID,document_id,task_id,task_category,timestamp,donation_data,attentionCheck,charityFeedbackPositive,charityFeedbackNegative,adSource,adSourceReason,recipeUsed,EA1,EA2,EA3,IA1,IA2,IA3,BI1,BI2
0,607778a26ff3de83125f50c5,66c5a13c86c57a87db6f59d9,ENG,ENG,{'$date': '2024-09-04T18:46:18.789Z'},0.0,WWF,NaN,NaN,AS1,It seems generic.,['RU2'],1,1,1,4,3,3,2,2

In [69]:
donation_survey_data_t[donation_survey_data_t['PROLIFIC_PID']=='66a8bb91c8dd777c3a9a838d']

Empty DataFrame
Columns: [PROLIFIC_PID, document_id, task_id, task_category, timestamp, donation_data, attentionCheck, charityFeedbackPositive, charityFeedbackNegative, adSource, adSourceReason, recipeUsed, EA1, EA2, EA3, IA1, IA2, IA3, BI1, BI2]
Index: []

In [31]:
donation_survey_data['attentionCheck'].value_counts()

attentionCheck
WWF    727
Name: count, dtype: int64

In [7]:
donation_survey_data['PROLIFIC_PID'].unique().shape

(715,)

In [8]:
donation_survey_data[donation_survey_data[['PROLIFIC_PID']].duplicated()]['document_id'].value_counts()

Series([], Name: count, dtype: int64)

In [9]:
donation_survey_data = donation_survey_data.drop_duplicates(subset='PROLIFIC_PID')

In [ ]:
donation_survey_data['PROLIFIC_PID'].tolist()

In [7]:
inserted_docs = pd.read_csv('../data/buckets_combined/master_docs_with_basic_formatting_0109.csv')

In [66]:
valid_data = donation_survey_data['document_id'].value_counts().reset_index()
valid_data.rename(columns={'document_id':'_id'}, inplace=True)

In [67]:
inserted_docs = inserted_docs.merge(valid_data[['_id','count']], on='_id', how='inner').reset_index(drop=True)

In [68]:
inserted_docs['view_count'] = inserted_docs['count']
inserted_docs

,_id,task_id,content,task_category,view_count,count
0,66c5a13c86c57a87db6f59d9,ENG,Join hands with us in protecting our planet's ...,ENG,5,5
1,66c5e4be2f44d7b54f76e52d,ENG,In a time of uncertainty for the future of our...,ENG,4,4
2,66c5a21086c57a87db6f59e1,ENG,We are at a critical juncture where our inacti...,ENG,4,4
3,66c88773e46942c099b32393,ENG,As you consider donating to the World Wildlife...,ENG,5,5
4,66c5a3e386c57a87db6f59f9,ENG,\n\nThe World Wildlife Fund (WWF) is a beacon ...,ENG,4,4
...,...,...,...,...,...,...
124,d1dce0f4179c433fb521b0d9_LLM,ESP_LLM,**Únete a la lucha por el futuro de nuestro pl...,ESP,5,5
125,95334737950147229a304e3d_LLM,ESP_LLM,**¡Sólo tú puedes hacer la diferencia para el ...,ESP,5,5
126,66341865cc824405b264f493_LLM,ESP_LLM,**¡Un Mundo en Armonía con la Naturaleza!** ¿Q...,ESP,4,4
127,e28ebe40ff3b4761aa28ef67_LLM,ESP_LLM,**Unamos Nuestros Esfuerzos para Proteger el P...,ESP,5,5
128,4ff91bcf8009404cb25834c5_CONTROL,CONTROL_ENG,The mission of World Wildlife Fund is to conse...,ENG,79,79

In [69]:
inserted_docs[['task_id','view_count']].value_counts()

task_id      view_count
ENG_1        5             15
ESP_2        5             14
ESP_1        5             14
ENG_No_LLM   5             13
ENG          5             13
ENG_LLM      5             12
ENG_2        5             12
ESP_LLM      5             10
             4              6
ENG_LLM      4              4
ENG_2        4              4
ENG          4              3
ENG_No_LLM   4              3
ESP_1        4              2
ESP_2        4              2
ENG_1        4              1
CONTROL_ENG  79             1
Name: count, dtype: int64

In [70]:
inserted_docs.drop(columns='count', inplace=True)

In [71]:
inserted_docs.loc[inserted_docs['task_id'] == 'CONTROL_ENG', 'view_count'] = 4

In [72]:
inserted_docs.to_csv('../data/buckets_combined/last_few_points_4.csv', index=False)

In [10]:
donation_survey_data['task_id'].value_counts()

task_id
ENG_2          82
ENG            81
ENG_1          81
CONTROL_ENG    81
ENG_No_LLM     80
ENG_LLM        80
ESP_2          78
ESP_1          78
ESP_LLM        74
Name: count, dtype: int64

In [32]:
data = []
directory = '../data/stage2/participants_info'
for files in os.listdir(directory):
    # Construct the path to participant_info.json
    file_path_acitivity = os.path.join(directory, files)
    data.append(pd.read_csv(file_path_acitivity))


participant_info_donation = pd.concat(data)

In [33]:
os.listdir(directory)

['prolific_export_66d82b36e3cb5863a2e34f1e_latest.csv',
 'prolific_export_66d82b4cc966a4c9bd40b1d6_latest.csv',
 'prolific_export_66d8461863df672d5ffe15b2.csv',
 'prolific_export_66d847204c5ed7a7e6ccde9c.csv',
 'prolific_export_66da0919e851f937a374e9ae.csv',
 'prolific_export_66da0919e851f937a374e9ae_2.csv',
 'prolific_export_66da0919e851f937a374e9ae_3.csv',
 'prolific_export_66dc76472d01a727b89d478b.csv',
 'prolific_export_66dc76472d01a727b89d478b_1.csv',
 'prolific_export_66dc76c126643b761a79ac7a.csv',
 'prolific_export_66dc76c126643b761a79ac7a_1.csv',
 'prolific_export_66dc76c126643b761a79ac7a_2.csv',
 'prolific_export_66dc76c126643b761a79ac7a_3.csv']

In [51]:
files

'prolific_export_66dc76c126643b761a79ac7a_2.csv'

In [7]:
participant_info_donation.head(1)

,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
0,66d8aada249ee85016de682b,668c1a52c95299c755900371,AWAITING REVIEW,Not Applicable,2024-09-04T18:45:52.229000Z,2024-09-04T18:48:43.318000Z,NaN,2024-09-04T18:48:58.235164Z,172.0,C127DB3G,42,24,Female,White,United States,United States,United States,English,No,DATA_EXPIRED

In [34]:
participant_info_donation.shape

(1169, 20)

In [52]:
donation_survey_data.shape

(727, 20)

In [35]:
valid_list_participant_info = participant_info_donation[participant_info_donation['Participant id'].isin(donation_survey_data['PROLIFIC_PID'].tolist())].drop_duplicates(subset='Participant id')

In [36]:
t = participant_info_donation[participant_info_donation['Participant id'].isin(donation_survey_data['PROLIFIC_PID'].tolist())]

In [37]:
t['Status'].value_counts()

Status
AWAITING REVIEW    945
RETURNED             8
TIMED-OUT            2
Name: count, dtype: int64

In [38]:
valid_list_participant_info['Status'].value_counts()

Status
AWAITING REVIEW    723
RETURNED             4
Name: count, dtype: int64

In [39]:
t['Participant id'].unique().shape

(727,)

In [40]:
t = t.drop_duplicates(subset='Participant id')

In [45]:
t.to_csv('../output/paper_output/stage2_participant.csv',index=False)

In [41]:
returned_pid = t[t['Status']=='RETURNED']['Participant id'].tolist()

In [42]:
returned_pid

['60ff4947f329136761a45103',
 '61549a2caa92d84f392000e9',
 '627ac8ebd1a87f7ea43604e7',
 '65e18d62c5a884a634501922']

In [15]:
donation_survey_data[donation_survey_data['PROLIFIC_PID'].isin(returned_pid)].shape

(7, 20)

In [43]:
donation_survey_data = donation_survey_data[~donation_survey_data['PROLIFIC_PID'].isin(returned_pid)]

In [44]:
donation_survey_data['task_id'].value_counts().reset_index().sort_values('task_id')

       task_id  count
7  CONTROL_ENG     80
3          ENG     80
0        ENG_1     81
2        ENG_2     81
6      ENG_LLM     80
5   ENG_No_LLM     80
1        ESP_1     81
4        ESP_2     80
8      ESP_LLM     80

In [18]:
donation_survey_data.shape

(720, 20)

In [67]:
donation_survey_data[donation_survey_data['task_id']=='ESP_1'].groupby('document_id')['PROLIFIC_PID'].count()

document_id
66c6e7186db9c208f260cabe    5
66c6eb886db9c208f260cad2    5
66c6f8696db9c208f260caf5    5
66c6fd416db9c208f260cb05    6
66c70f016db9c208f260cb22    5
66c71a176db9c208f260cb42    5
66c730526db9c208f260cba4    5
66c74f216db9c208f260cc0c    5
66c757f06db9c208f260cc32    5
66c7c396f837defabd5eb8a7    5
66c9520cb087a0712a44d233    5
66d2ccdb3ef557a33f96df8e    5
66d3c06b5a434c9ed85a6834    5
66d3c3775a434c9ed85a683a    5
66d3c6d95a434c9ed85a6842    5
66d3c85f5a434c9ed85a684b    5
Name: PROLIFIC_PID, dtype: int64

In [77]:
t = donation_survey_data[donation_survey_data['document_id']=='66c6fd416db9c208f260cb05']
t['timestamp'] = t['timestamp'].apply(ast.literal_eval)
t['timestamp'] = pd.to_datetime(t['timestamp'].apply(lambda x: x['$date']))
t_sorted = t.sort_values(by='timestamp')
t_sorted

C:\Users\shrey\AppData\Local\Temp\ipykernel_32340\217154130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['timestamp'] = t['timestamp'].apply(ast.literal_eval)
C:\Users\shrey\AppData\Local\Temp\ipykernel_32340\217154130.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['timestamp'] = pd.to_datetime(t['timestamp'].apply(lambda x: x['$date']))

,PROLIFIC_PID,document_id,task_id,task_category,timestamp,donation_data,attentionCheck,charityFeedbackPositive,charityFeedbackNegative,adSource,adSourceReason,recipeUsed,EA1,EA2,EA3,IA1,IA2,IA3,BI1,BI2
611,6463c107f7da96b246f9ad52,66c6fd416db9c208f260cb05,ESP_1,ESP,2024-09-04 22:55:18.441000+00:00,0.5,WWF,Me gusto la comparacion que se hizo sobre los ...,No me gusta que habla sobre la conservacion de...,AS2,"Porque habla sobre sentimientos propios, lo qu...","['RU2', 'RU6']",2,1,2,4,2,4,2,2
612,66bb9c7f501107c4829068b9,66c6fd416db9c208f260cb05,ESP_1,ESP,2024-09-05 00:29:30.545000+00:00,1.5,WWF,La maravillosa tarea de conservar la naturalez...,NaN,AS1,Pienso por que olvido poner los acentos corres...,"['RU5', 'RU1', 'RU6']",4,4,4,4,4,4,4,4
613,664a145511338d9b7165824c,66c6fd416db9c208f260cb05,ESP_1,ESP,2024-09-05 03:00:01.752000+00:00,1.5,WWF,"Me gusta ayudar los animales, que no se pueden...",NaN,AS2,Es lo que hace WWF,['RU5'],5,5,5,4,3,4,5,3
614,652e8b28a8cbaf32300b45fd,66c6fd416db9c208f260cb05,ESP_1,ESP,2024-09-05 16:30:12.910000+00:00,1.5,WWF,NaN,La redacción es deficiente.,AS2,"Se nota que lo escribió una persona joven, sin...",['RU7'],4,4,4,3,3,4,4,4
615,6633a0e8efe1d018ea99bfc9,66c6fd416db9c208f260cb05,ESP_1,ESP,2024-09-07 02:55:20.072000+00:00,1.0,WWF,NaN,na,AS2,se siente mas personal,"['RU1', 'RU3', 'RU6']",5,5,5,4,4,3,3,5

In [64]:
donation_survey_data[donation_survey_data['PROLIFIC_PID'].duplicated()]

Empty DataFrame
Columns: [PROLIFIC_PID, document_id, task_id, task_category, timestamp, donation_data, attentionCheck, charityFeedbackPositive, charityFeedbackNegative, adSource, adSourceReason, recipeUsed, EA1, EA2, EA3, IA1, IA2, IA3, BI1, BI2]
Index: []

# 6611dfa4198eb84743071561 valid but extra

In [45]:
donation_survey_data = donation_survey_data[donation_survey_data['PROLIFIC_PID']!='6611dfa4198eb84743071561']

In [46]:
donation_survey_data['task_id'].value_counts().reset_index().sort_values('task_id')

       task_id  count
7  CONTROL_ENG     80
2          ENG     80
0        ENG_1     81
1        ENG_2     81
6      ENG_LLM     80
5   ENG_No_LLM     80
4        ESP_1     80
3        ESP_2     80
8      ESP_LLM     80

In [76]:
donation_survey_data[donation_survey_data['task_id']=='ENG_1'].groupby('document_id')['PROLIFIC_PID'].count()

document_id
66c6181507bfd712ba618584    5
66c627b607bfd712ba6185cc    5
66c6302d07bfd712ba6185e3    5
66c685cc6db9c208f260ca3a    5
66c6978c6db9c208f260ca68    5
66c71e356db9c208f260cb5a    5
66c7374d6db9c208f260cbc8    5
66c74aea6db9c208f260cbfe    5
66c78f7df837defabd5eb804    5
66c7905af837defabd5eb80a    5
66c7a4bdf837defabd5eb863    5
66c7a655f837defabd5eb872    6
66c7a8a6f837defabd5eb887    5
66c7aa3ef837defabd5eb88b    5
66c7d114f837defabd5eb8b6    5
66c7de66f837defabd5eb8c1    5
Name: PROLIFIC_PID, dtype: int64

In [79]:
t = donation_survey_data[donation_survey_data['document_id']=='66c7a655f837defabd5eb872']
t['timestamp'] = t['timestamp'].apply(ast.literal_eval)
t['timestamp'] = pd.to_datetime(t['timestamp'].apply(lambda x: x['$date']))
t_sorted = t.sort_values(by='timestamp')
t_sorted

C:\Users\shrey\AppData\Local\Temp\ipykernel_32340\3248691735.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['timestamp'] = t['timestamp'].apply(ast.literal_eval)
C:\Users\shrey\AppData\Local\Temp\ipykernel_32340\3248691735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['timestamp'] = pd.to_datetime(t['timestamp'].apply(lambda x: x['$date']))

,PROLIFIC_PID,document_id,task_id,task_category,timestamp,donation_data,attentionCheck,charityFeedbackPositive,charityFeedbackNegative,adSource,adSourceReason,recipeUsed,EA1,EA2,EA3,IA1,IA2,IA3,BI1,BI2
101,66d6afc8fc2d22bb7acdff2c,66c7a655f837defabd5eb872,ENG_1,ENG,2024-09-04 21:19:16.006000+00:00,1.0,WWF,I support wildlife and conservation efforts by...,The solicitation didn't move me to action like...,AS1,Just the cold unemotional style of the writing.,['RU5'],2,3,3,2,2,2,2,2
102,5fb41bf3f84c7006ac8e30f2,66c7a655f837defabd5eb872,ENG_1,ENG,2024-09-04 22:43:32.418000+00:00,0.0,WWF,NaN,NaN,AS2,It doesnt sound like an AI,['RU7'],4,4,2,4,2,2,1,4
103,63c047ef36e1348b19bb8010,66c7a655f837defabd5eb872,ENG_1,ENG,2024-09-04 22:59:21.990000+00:00,1.5,WWF,tangible impact on protecting wildlife and the...,"The climate, trees and plants - I wish they al...",AS1,I assume at this point everything is being wri...,['RU7'],5,5,5,4,4,4,3,3
104,661e47e87d86f5629af43921,66c7a655f837defabd5eb872,ENG_1,ENG,2024-09-04 23:20:10.618000+00:00,0.3,WWF,I liked that the ad was written in a way that ...,I absolutely hate that the ad doesn't specify ...,AS2,"It's pretty difficult to truly know, so I gues...",['RU2'],4,4,4,1,1,1,2,4
105,5e7072e5fb136c63e94f3fa4,66c7a655f837defabd5eb872,ENG_1,ENG,2024-09-05 10:50:29.702000+00:00,0.0,WWF,their conservation efforts,lack of transparency around donation percentag...,AS2,it feels vivid and lifelike in the writing form,['RU2'],3,2,3,3,3,4,2,2
106,606cba49bb285f26a3afee25,66c7a655f837defabd5eb872,ENG_1,ENG,2024-09-07 16:23:36.412000+00:00,1.0,WWF,NaN,NaN,AS1,It did not sound like something written by a h...,['RU2'],3,4,4,4,4,4,4,4

In [47]:
donation_survey_data = donation_survey_data[donation_survey_data['PROLIFIC_PID']!='606cba49bb285f26a3afee25']
donation_survey_data['task_id'].value_counts().reset_index().sort_values('task_id')

       task_id  count
7  CONTROL_ENG     80
1          ENG     80
3        ENG_1     80
0        ENG_2     81
6      ENG_LLM     80
5   ENG_No_LLM     80
4        ESP_1     80
2        ESP_2     80
8      ESP_LLM     80

In [82]:
donation_survey_data[donation_survey_data['task_id']=='ENG_2'].groupby('document_id')['PROLIFIC_PID'].count()

document_id
66c6eb326db9c208f260cacf    5
66c6ef3c6db9c208f260cadb    5
66c6fb5d6db9c208f260caff    5
66c6fe226db9c208f260cb0c    5
66c711cc6db9c208f260cb2a    5
66c71e1a6db9c208f260cb58    5
66c7333c6db9c208f260cbc1    5
66c750f16db9c208f260cc18    5
66c75a3c6db9c208f260cc38    6
66c7c5a0f837defabd5eb8ac    5
66c958a5b087a0712a44d238    5
66d2d0393ef557a33f96df94    5
66d3c7e95a434c9ed85a6847    5
66d3c8af5a434c9ed85a684e    5
66d3c8b05a434c9ed85a684f    5
66d3ca8a5a434c9ed85a685a    5
Name: PROLIFIC_PID, dtype: int64

In [83]:
t = donation_survey_data[donation_survey_data['document_id']=='66c75a3c6db9c208f260cc38']
t['timestamp'] = t['timestamp'].apply(ast.literal_eval)
t['timestamp'] = pd.to_datetime(t['timestamp'].apply(lambda x: x['$date']))
t_sorted = t.sort_values(by='timestamp')
t_sorted

C:\Users\shrey\AppData\Local\Temp\ipykernel_32340\3703377181.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['timestamp'] = t['timestamp'].apply(ast.literal_eval)
C:\Users\shrey\AppData\Local\Temp\ipykernel_32340\3703377181.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['timestamp'] = pd.to_datetime(t['timestamp'].apply(lambda x: x['$date']))

,PROLIFIC_PID,document_id,task_id,task_category,timestamp,donation_data,attentionCheck,charityFeedbackPositive,charityFeedbackNegative,adSource,adSourceReason,recipeUsed,EA1,EA2,EA3,IA1,IA2,IA3,BI1,BI2
253,66a79366e9d1eb8c901a2b23,66c75a3c6db9c208f260cc38,ENG_2,ENG,2024-09-04 22:39:16.268000+00:00,0.7,WWF,it was informative and persuasive,NaN,AS1,"while it seemed persuasive, it couldn't really...",['RU5'],4,4,4,3,4,4,3,3
254,66413abd57f96e210a9cfe13,66c75a3c6db9c208f260cc38,ENG_2,ENG,2024-09-04 22:48:29.310000+00:00,0.0,WWF,I like that it is a wild life protection agenc...,I wish they would go more in detail on the thi...,AS2,I don't know just seems like it might possibly...,['RU6'],4,3,3,2,2,3,4,4
255,5cb1cd86637a05000187532b,66c75a3c6db9c208f260cc38,ENG_2,ENG,2024-09-04 23:06:28.851000+00:00,0.1,WWF,supports conservation efforts,I prefer local charities,AS1,"Not very emotional, seems predictable.",['RU6'],3,2,2,3,4,3,1,1
256,647b7636ede61061e7e37f70,66c75a3c6db9c208f260cc38,ENG_2,ENG,2024-09-04 23:22:30.516000+00:00,0.5,WWF,I would have liked to see specific examples of...,No specifics. Broad strokes.,AS1,Just does not comvey much emotion. Just facts ...,['RU6'],2,3,2,3,2,2,2,2
257,6690119d84f6b9351feaa95d,66c75a3c6db9c208f260cc38,ENG_2,ENG,2024-09-05 11:59:28.183000+00:00,0.1,WWF,"I liked the ""become a voice for those who cann...",NaN,AS2,Simply that it just feels human.,['RU6'],3,3,4,3,4,3,1,4
258,66bb969b0e3ce4bd22550bd9,66c75a3c6db9c208f260cc38,ENG_2,ENG,2024-09-07 16:26:09.416000+00:00,0.8,WWF,I loved how the advertisement stresses ethical...,One area for improvement is the lack of partic...,AS2,"I chose ""Human"" because the commercial has a c...",['RU1'],4,5,4,4,4,4,5,4

In [48]:
donation_survey_data = donation_survey_data[donation_survey_data['PROLIFIC_PID']!='66bb969b0e3ce4bd22550bd9']
donation_survey_data['task_id'].value_counts().reset_index().sort_values('task_id')

       task_id  count
7  CONTROL_ENG     80
0          ENG     80
2        ENG_1     80
4        ENG_2     80
6      ENG_LLM     80
5   ENG_No_LLM     80
3        ESP_1     80
1        ESP_2     80
8      ESP_LLM     80

In [56]:
donation_survey_data.to_csv('../output/paper_output/stage2_donation_final_filtered.csv',index=False)

In [51]:
final_people = t[t['Participant id'].isin(donation_survey_data['PROLIFIC_PID'].tolist())]

In [52]:
final_people['Status'].value_counts()

Status
AWAITING REVIEW    720
Name: count, dtype: int64

In [27]:
final_people[final_people['Participant id']=='66b7aca57d8317c2a800416a']

,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
51,66d8f8abae1708760e50ad4c,66b7aca57d8317c2a800416a,AWAITING REVIEW,Not Applicable,2024-09-05T00:18:21.773000Z,2024-09-05T00:21:08.488000Z,NaN,2024-09-05T00:22:27.727148Z,167.0,C1MGNTBM,99,18,Male,White,United States,United States,United States,Spanish,Yes,Unemployed (and job seeking)

In [55]:
final_people.to_csv('../output/paper_output/stage2_participant.csv')

In [57]:
set(final_people['Participant id']) - set(donation_survey_data['PROLIFIC_PID'])

set()

In [58]:
set(donation_survey_data['PROLIFIC_PID']) - set(final_people['Participant id'])

set()

In [59]:
final_people['Participant id'].to_list()

['665221f0996f9daef629b186',
 '661b3299bf19db77d7412b86',
 '66c4d2c2713b223511e4e676',
 '5ed5d8efa94646024eec6e36',
 '66687cd6888ba007257ad760',
 '66aa59612e8897c5ab69032a',
 '6441d29dcc9aa739e6d4b39d',
 '669eefa65a5c5d4624a3198a',
 '66c7168869bba7cea5a4b4d2',
 '5c917c0cd2c7770001064e77',
 '6679f19d2b337bb18d2d584b',
 '548491acfdf99b0379939cc0',
 '63d96d5957cdd8a417721253',
 '63c047ef36e1348b19bb8010',
 '66656266d09c8744714c7b20',
 '60be9e6d43e65ef1e1082a0a',
 '5eba34aa6f816b16d72f49e1',
 '5b1edbdc5e45c000012a9c57',
 '5a8c2da3eea3d300016ea27c',
 '66751182f21224f506c8d043',
 '6689b775decbc522030ddc73',
 '66799ffc3eafbd87ded4cd94',
 '64451c0fc0996ad3708184b9',
 '5dd6f8cb1986eb69959091b1',
 '66d1c54aefc822473cad25e0',
 '667c7af1dd68609d9bfe34ca',
 '5ab942eca3ba7a0001b41f88',
 '60451e0f0d94f161286383d9',
 '65fc7aadeb5d3f4ae108f25e',
 '66884d036c4d24aaba02c702',
 '5ab99e8247a9f7000153b5d3',
 '5ef0fa1b7d17e30b4204723f',
 '655fd05c12d38751dfa91559',
 '66310fa796927ce79774380d',
 '5e5291ff6c3d7d2a79ec869e',
 '665cb05e52e7db08e6e92508',
 '6604543713f81bf1906dd444',
 '65d52f9d73f681d2d35ebbfc',
 '5e648efca8c76520c918bb31',
 '5eda86226763346ac679ca5f',
 '605f6da0cd9fe55d6a6f3b90',
 '614e8713ba7000ac40031538',
 '603fcfc8b2061a10b80460e6',
 '668696f692c9437b43935373',
 '668c430900cdd639aae2b7d7',
 '623488cb1417a113ca966af3',
 '663e5cf06229dbbedcd83aeb',
 '5dc5bafe76244042b6b3b83f',
 '66b8f9c004ccf3f1d193a6a9',
 '665e63b5ae7eaef8de21ab25',
 '616668857d426d6925dacbe6',
 '5d93aeb1cec22300195493fc',
 '66a79366e9d1eb8c901a2b23',
 '66687940b6066d0b32735285',
 '66d878851a20661f31eb775a',
 '66368f33e88100726ec243d7',
 '668d8437daa045900cd211e0',
 '59e833e72f63d30001c8fb86',
 '6604586301474ab62d19f123',
 '6632a68dd977c623f763a41a',
 '65205f42ac9a536a06ea7c37',
 '64401b5576e7ee7ff9dc040d',
 '63e0356f54ac35f09d69ca49',
 '6561042cb3cd24f4432bf584',
 '5dd61f689740545c506ee244',
 '668467c29cba21eb0c3c9aca',
 '59d0ec2446447f00011f0254',
 '63af5c586c05eee8c3d03730',
 '66413abd57f96e210a9cfe13',
 '63bca22d6fa8440663c937f1',
 '60bd3949b6f6d9c3453e8def',
 '5fb41bf3f84c7006ac8e30f2',
 '66d2af66151a540b5d622d36',
 '6314d97aa02af651ea1a9591',
 '667cb46a29b1416537072c90',
 '63bf745cc01669a110ec48ba',
 '66ab741a8d04527401802317',
 '66299dc31130ad434839ad7d',
 '663d6279f372d5e7ae867917',
 '5dd38420a71de83809342ca3',
 '6652583f062d6f7b7d78f409',
 '653fc86bca5191a208252115',
 '65dca2a6e767214dee312631',
 '632fa9e40fa5b8393ed87659',
 '66a52bb0e95dee7a728e1892',
 '5ce9be3a7d69950001cd9959',
 '664d46ad7cc1780eecfd0c24',
 '66ad4335036dc64615abb440',
 '628e24c80b3e2b2e0d7a5af1',
 '66c50b7af34fd922784167ce',
 '5feaa1772178d1ae84391de6',
 '63d84be2c9a21026d442e728',
 '613d40ff7075fec0a00560a4',
 '5cc8f511f24f6c001c1692a9',
 '6463c107f7da96b246f9ad52',
 '61006354df5cc79f96d0660c',
 '6007776684975127676717c4',
 '66b5a7ae36e5b931db863954',
 '663bb5fefba87a86bd9a723f',
 '6658d773729ddb9f5891335d',
 '6305235d094b81500c5e3371',
 '607778a26ff3de83125f50c5',
 '5ccafee43a7dbb0016546263',
 '611087db754dae727592763b',
 '66d7d7d2751da21eec22043b',
 '63d1477e452a9d7e822b79a8',
 '66d7d94ecf4c9082e82203be',
 '599ba05e05a0e30001f20344',
 '66d6afc8fc2d22bb7acdff2c',
 '65de422405a3595138be9b02',
 '65c1184408364a3a90a58786',
 '65ce19f79d8488ef10b52a3e',
 '6681c05c715c05de75f4ca0a',
 '6100c28ed43a1dea00f08633',
 '63eab79dbbee48659db0dcc4',
 '66d688b3b7b4aa17e073d128',
 '5fb2c8b4b04a8594fc0a3825',
 '66116efa868be6ac623de9fc',
 '66706191120230e6a89ddd0e',
 '66d7e189b4be3f503a2f230e',
 '66c63537c2829ac9fbbd9d5a',
 '66d8dccedad500ed9838cc6d',
 '66cb1eb8bf54a70914bbf1c8',
 '6655e61b775a076348a40b8d',
 '66bcbbd35d182838b25ff7df',
 '66359b64b4ef2e1f0830f5aa',
 '665e0790251ba96fa62b621c',
 '6629495997804a137f1cc8cb',
 '66b07f4e98d4f80738e8cc4d',
 '6697de4d08ef9922b2bc531a',
 '601750d7a0361e9a5e4fdc56',
 '6657368915008a8a9edc91a9',
 '6668c95f0adc056c9c178af2',
 '633c7424294f7a26710ca395',
 '66d7c1a21baad48e845dfdb0',
 '66240f705ac353a0bb928773',
 '629082739390703f993b12bd',
 '66ad6ef729911029f1357254',
 '5e07a94db7b33010fe2af9b4',
 '663c8bf2f8c29a144dc191de',
 '66d795e88a5d1559abbf5898',
 '63f7b8c25fc05973386fcdff',
 '631ff899c56260cb62016bca',
 '66d66b8e044e8ec3d8f4244e',
 '5d59d1c4f6a63300198681e8',
 '5f38e87099a44d40b79e5009',
 '66af3f96e50600f8f0da239a',
 '667ed5ce384ed14d7fddc226',
 '63ef5d25e9b2814388fe79d4',
 '66ba6496402d8157cdf92e7f',
 '5bc13b08f7ea0800019f91cd',
 '66d67902c511907836bec93b',
 '666f33fd54f65acc05b4c7b1',
 '665cea26beb2274c6c616503',
 '66c7e6e05a6d60e4278bfda7',
 '66633d2369f9da53edec1a9b',
 '65ea0eccf8677048425a4d2c',
 '55a35906fdf99b244bc18dc2',
 '62d38f10654f3fc8a393b551',
 '65f227fd72ee1b23f6640b5f',
 '65103482eef061cb1e3efb85',
 '66652ccee12aa31e8ff9fb38',
 '6113ff4bca90f6632e738e80',
 '60de1e91d169070d449d6c38',
 '66d1f88853da09348a20fbe8',
 '669ecc103e43370cd5ace699',
 '634f87d42fa897f3a8e3acad',
 '5c95970cd676900016e1a940',
 '5dc3552003f8562725a1b956',
 '62e3007fd78a0537dbe4fcbd',
 '5c2c62542c45d400014a32e6',
 '5c3b8e621ede2b00011604a9',
 '665531c847ff8f8d30f3425b',
 '653aac633ba278e5620ac9a9',
 '663bec51775d063f6fef7c82',
 '6019a44e01bf1810d777c4f8',
 '66c93b1e2e5675d92d52a64c',
 '6161e61324cc141a88e2d113',
 '66467574dad014b033fa664c',
 '5f879df674a3c81e20a40cd6',
 '66c5ea1ab6ff3306cd7b3bf6',
 '5ee3f2b74e35580dd5dc0925',
 '65f8e54f7d38e43856619feb',
 '5c78b032419dcc0014119082',
 '569b1e1aaf9ad7000d640f24',
 '6291293b4da216ae257c1867',
 '669519293719d01c2fdd1311',
 '661571d6cc16ee34676734df',
 '66a40d5dbd4e4f462556a4b1',
 '6650e04237e2aa9bd22fbfa4',
 '5cb1cd86637a05000187532b',
 '64485d7e807fdd8adea9db1d',
 '6672f62271d76001fb79f37c',
 '64eede50d732cf4ab3e590ad',
 '66c15c3ed1ed55387c5e03ef',
 '665f1309c64c2a4f4ea7bb91',
 '65e8d07f6dee8323f49a2b5b',
 '61282ca83be28773ac7c421f',
 '61118b5fd788969295997051',
 '5c054e8a553fb800011917d7',
 '66106c77782f1ef90fde89fa',
 '66d76a563b4869285ea98eea',
 '60fddd1ef83cc16b0411a2ba',
 '5a87b173b093f80001a7ece9',
 '643abe2183fc66157d8b0b9c',
 '5e120ac3ac9e168a3f6ded71',
 '63951be9d0b111f5fbab5eba',
 '5ec17a2e02be030625eaff6e',
 '60b9af795939f976cb74232a',
 '65cd1e75829ba4e3af71c2e5',
 '59ab51535e7f4800010eeed9',
 '62d5614f8e0bad3405c9dac9',
 '63e56678a87f209e2ca83059',
 '6632ba81acfa4541302b92d3',
 '60e7858c8bb1e77a5eee77de',
 '66577b8c804307020201a131',
 '5e7b815adb5aba05af6e6cc7',
 '5adc104b09eae2000112bd76',
 '61bb3a4f40db417c1a138ff4',
 '6339d15f5c1c670b3075f0fc',
 '5955a3eb98c9c400019f5c5f',
 '5c9a7872e2a8d00001585513',
 '5bd47734506cd3000101d181',
 '608f2aa883599160c8b87a79',
 '65cd5718a085f2323aad42de',
 '663294a9baf0036a40ac21a1',
 '66465a9ce1c681c9cbb78eca',
 '5f51404f39052135153b52b9',
 '5eb6f666c792cd6143878d27',
 '65464b7e526b25cfc1dfeeb2',
 '6298fbc8e35ae6800ccb3128',
 '65d50e7a510f38650aa5340c',
 '66815b1c397783d282513fb3',
 '6312c4daeb7e0f890b0b6a7f',
 '6340b7955ab968e4426eb476',
 '655cc974613aec120f21293b',
 '663a5fa6c0dd77f659a12550',
 '66c35f5caa40f6de28800d89',
 '665fe1a6172b55ef78d5256d',
 '5f836dbde582bf4f666b121e',
 '63f049c2d78b2bc822a16dac',
 '610e0dc76d43ecb6fea93855',
 '5f49f3262a3d07563d14a7f1',
 '5ee642c9f5cb343a58b1ef13',
 '5c7160b5b2516100015dfef1',
 '5c4e31b37065de00011f795d',
 '571c631fe1d2ec0013a68515',
 '62c65cd877b056c782d09fe1',
 '62e0326dbbda328df3ceade2',
 '667b2f1ebd0fe96b4afb83f5',
 '62349f9ac56251496a619264',
 '664c4e829445321c23a8de52',
 '669864e93f0ed6ee2a5d5cf8',
 '5e8fc5254447f82b9defc6b6',
 '66beefb9ec97ba13af1e64a8',
 '661e47e87d86f5629af43921',
 '665a433b5cf2b3fc75ec044e',
 '647b7636ede61061e7e37f70',
 '63bb98852cdc67dece8adb8e',
 '65b6dc6d9d685626cfef6857',
 '5dd1df8fb48da3240ca85c45',
 '6670b79e8456b0e5b1799c2f',
 '558cdd7efdf99b0f1cc5f4c1',
 '5e29c3e725dcfd01cef9f474',
 '63d98dcfa03c130e4599a907',
 '66293ab31f96fbbb4de50cb8',
 '66d8a09ce863659174f128cb',
 '66baaf7d1605ec806a07dc95',
 '65ca661975a7293b28a6efab',
 '5e1a7114a90da52e206de7ea',
 '66528148e922e522ab6fb4a9',
 '603ee4c2bd61ee1a08fd6a8a',
 '5ef42ba59401801d9f859e2d',
 '66439df8cecf5fd276606155',
 '6417dfab27377aff2c54af66',
 '6646728bbfb8084f4f45c0a7',
 '669c1bc6a24652548784f3fc',
 '5e48d3d8b26b05361ff522f2',
 '66d7259966407c81ec7fa46b',
 '6391a4d41c7025c8ad3d3e18',
 '66a2bc32533a358316cb9011',
 '61122e429887afaa2d131b09',
 '6535a4e5ea3f8466589b9aa0',
 '668cbad24e74402459631c48',
 '62da4563028fbcadf46412bc',
 '640415971520c41606ca4389',
 '665f9b37bc3065fed261e81c',
 '63f38cea3d56eac0c02a6eeb',
 '5b4eed90995d4e00010949b7',
 '63f2261685a2effaa7a16de6',
 '5c7cc4d59f29bd0018349603',
 '5a0c63e15d06850001affd96',
 '66c42da12cca15dd8d446e9a',
 '6664e5e07f6c9e89bdf50390',
 '6629b763d3f3a403d4a694d5',
 '66d3482fd505014e8eb8f424',
 '62e9c91168f8d1ff048964e9',
 '6569f997c88032b4981a222b',
 '56fb454534a0d300061a5070',
 '66d8b618dfe68065d1aa4a90',
 '65da7c7c8f8bac48599b274a',
 '559ea6e7fdf99b0fff2bda68',
 '600473adcef0ed5bbd905567',
 '60ba2ffd080107de026041d3',
 '665e2af7cff6620a57b2fd1c',
 '65a6b92c9a480cc6d7033b24',
 '5e405a1cfce14d29997364da',
 '6645ef6d923500eddcdc83ad',
 '5ef9302c07b0e310918662c3',
 '66277673bef725be86e38ffe',
 '66a684aaffcd837b0903b577',
 '66d916af0cf8c145a0aa3220',
 '62a0294e78bac60d6f9c49df',
 '63cc5fddd5813c609d5b28d5',
 '66a550e404332e1b17dddaaa',
 '665bc39f3d681ec2ea290e4d',
 '614e6f4f00a9e94b123316d3',
 '66c819bf71a1c4f4c2e729ef',
 '66aa791b9241ed81569fdd81',
 '669ea85495cd550e1bf25229',
 '66979a6297fc39c552df1e50',
 '66ae0709d8dd8981a2d6ee04',
 '5e7072e5fb136c63e94f3fa4',
 '65cbda4ad8076d79e5fd763f',
 '53c04378fdf99b360e022d92',
 '6044051ef235ef46052ab305',
 '6543ae61df4c68a0e486942f',
 '636148a83d7a7c349bb08436',
 '663f6499a07afa04b277d7e2',
 '658ea5a4017996f2dc550d43',
 '665bbd41a94b64c42a276e1d',
 '61074ae762b0186a302f1028',
 '606e3ddf19540080228e3a0c',
 '66a43f5957b881066dfeb5f1',
 '5fa04f87861aca05fab63ece',
 '628f0d7e3055b5d1887916c5',
 '6465cd750298e0714b6391cf',
 '66cce12cdb6f0ccdfdf668f3',
 '6644f37947ff3c7c3f9bbca1',
 '611343cebd1f50c6a0eaaf8c',
 '66d35d240ba45109a3882554',
 '5e45477286e27102354a420b',
 '6163d3ea0d13c617bb46c99b',
 '66bc94bf776a4169d4b15b7c',
 '660aecfcef9da76dd04ce2b1',
 '5b9ee4918d042e0001403143',
 '5e4044797946592823cbec2a',
 '570bc1ffb9b52b00102db939',
 '65626cc8ce1eab7aaec3a55b',
 '655fa55ae220887674baf9d6',
 '6690119d84f6b9351feaa95d',
 '6643a14a5f8e3396daaf127b',
 '66c3e65e4204580dbb03c32f',
 '66d66592ecdb6fe3de954329',
 '5661bce973ac87001180413a',
 '5e8601d90126b207e8c7a2aa',
 '66d34b99f621a0e7de30c1c4',
 '5e7a258b1a7e1c069379711c',
 '66d5a7788efaeec1102dcca5',
 '669284a314b1e3282fce4afd',
 '66d5f10ce1fa44997a861736',
 '6138af26127651134a88842c',
 '66847b3e4dd65cfd282d2305',
 '662687fc152ffe3df23453e4',
 '66659e3342b581f199e47a4d',
 '65a2aeeaff22f2a843564a85',
 '6647be4e1c230cad2c31613f',
 '66a4b815bba4dad1e16b497d',
 '665a66d17224187f00fca42c',
 '65d0d9fb04480131348a4672',
 '64776e3beba1085215214ec0',
 '5c0f500787e876000151fc5f',
 '60a2a8570a0f9cc00d6b9d1a',
 '65f1b56d620b27328a8836e8',
 '56e019f1a3b147000bc63028',
 '663de3332de392974f96decd',
 '663e4b5deaf50d8cef5ee1cb',
 '666794e38a2ac585e818ba17',
 '63caca07727ec41e89a42b72',
 '663fd4658572150cc2416c27',
 '6151fbe0c6b5a6b6af706100',
 '65cf6bcf11dca2196c5f9156',
 '5d2fb8f7034d7d000164bd18',
 '65e25f1b19693f423350b1ee',
 '661f4cfbeabfb4f58a8ecb4c',
 '63175042914da36ed2656593',
 '665a234c97c127c4605a9be1',
 '5e4566e8f64db704b739b757',
 '667085cc6ecfc9326ff6de72',
 '66293ce3dba0764775195e58',
 '66c6ad713afa83a1ba517d18',
 '56f9364e895094000c8f4967',
 '66a9979ad8c56c6f29446781',
 '66880bd9fc1509787faaa118',
 '5ea7514665002511e3b2da95',
 '6691a24cc9b007edebddc34c',
 '668564a45368836193b94269',
 '5ef32f0aeb0c9103d56a8558',
 '667a1f5e23bc5cee5bdb0a89',
 '6526c3297277ece1f3273549',
 '6674d66310b6684b86ddf7b9',
 '5e2926d80beb030ede110e67',
 '663922bf1ff7589784c76f51',
 '65cbe8940549c170484ea078',
 '667c3c4d32f4b404c46e325d',
 '66bed1da4f4333c83ef1e0ea',
 '5be728a4dbedc80001377337',
 '6643a328878e4f517c10de28',
 '5e32f34f2a574a01ebf984ab',
 '66aa97f1b6f7b6d542d37218',
 '65e150a2cca2780f6d77dfa6',
 '6679b6e51b2f51950f21fd65',
 '667d76240f5000a33e44bbaf',
 '5d7e777d0cc1c900195d5fbb',
 '666f57dffab7d1fcb56c8b53',
 '6680d577ce8b233327b0272e',
 '66cbc2627559d53c0e3e4ac4',
 '6695745ee6d6f8975139350a',
 '614f6bad672ef7cf5ecfd965',
 '66b2611ba705781f5401b996',
 '664cfd560115ff4b3f239bb8',
 '663bab395c5db0c5bc0944d3',
 '5cc3f0f9fdb33500018c5eeb',
 '66d6376eb15526056851d558',
 '66bb1bf162053ffd1926cc75',
 '63d1650b103325686e22e3b7',
 '5d250d243eea32001a079a3b',
 '63b6643cdbd50289e125a3e3',
 '5df3dcdd9b92b12b6db3a4e5',
 '665b7b047373d8da553237a6',
 '66b2eec417dcf3fb31ba0b45',
 '663ad3521b3d8f4931d80cd1',
 '66b4bb38f52cc2a093610c8d',
 '6657501de9a93ec1dae74cac',
 '66bcd07706e06c4d51e4885d',
 '668d6ef4c3b0ea4e2540622c',
 '66cc97280604bbb0c7bc71bd',
 '66c7adc45a77680b4053f8e2',
 '65374e5ad78177a9fe89f1a7',
 '63df06a8c5ac5f3c6bf77e6f',
 '60fd83ff5af11073b7d1ed62',
 '668f13e7da1b33ec8a028623',
 '62ec1fe3ebd392c343d85886',
 '66abbaa7e79344e4b77a7834',
 '55ea70c37480920010aa9982',
 '5d9f8573ce3daf0015e3e400',
 '66bba9777e53db38261e7a85',
 '60bc011503db109b7d46851d',
 '66b3ca6ea28f2b7430c73be1',
 '6656b41a68bc810ea64c442c',
 '668cb8f2ae575baf6cad3f36',
 '665f97db56096b743c2332b1',
 '5aeaa1192ef8f800014af05c',
 '5cb5e6927a92c500015c0de1',
 '66bcf6ae07e40789d4193872',
 '6693fdc21180149dc7f6619e',
 '5d5f31230fc94a001c632b69',
 '58adfc6e7cf56d0001f931a2',
 '66cd38eeecc9bb2fbf5a16e9',
 '608437f0b139060610c9f0c1',
 '663d6bcb7380775c879d17fd',
 '56baafe430d6b3000cf857ea',
 '651c4484ba17050f6b716614',
 '66857af993dcf9649eefd9f5',
 '66316ac602a513e2e74d5bdc',
 '5d951ede9b6f880018f63b6e',
 '66952fa8c27023759f09cd9e',
 '5aa83a71f6dfdd0001eb1690',
 '5bd612ce860b840001dc1a74',
 '664fc6ec0beb5400a141b77b',
 '661415341b1fdb1844c6f6a6',
 '66894dee33c97ad934460664',
 '66c0d9ef3c9b1d596446f813',
 '5c1ebf5f658e9200017ae7e9',
 '5d5338103c1b020018f36359',
 '65fb580ab7fbb2d518ee8eaa',
 '5ceef17d410beb0001e40023',
 '6605c023887cc106775bc31e',
 '5d72f471515c8b0001ed07fc',
 '6634e43ac073310534c0f70f',
 '665d16039d6c17c10353748a',
 '5ec70d2d62e69c157fde4884',
 '652c821a3d99a68b56fe9bcb',
 '66310bce1a0c0e0801d40dd6',
 '5da956c25a994b001650f1e3',
 '657a4d49b830a8fb3ce40e38',
 '6567592c14d1295fa4280f34',
 '5c5f484f5cacd10001f1c1e0',
 '5dd5b42a2091e95798fbf574',
 '5f6be2474140c215c8ebbe52',
 '5ea450a034f3aa3f543e042f',
 '5e3bba50f0bf0f3d1856238e',
 '6654d2a81ff59c89050c1b01',
 '5e998f318e64b60009f048dd',
 '666e20c484d272cadcc536c9',
 '612039d9400fae9545b3c5a8',
 '661b0064eee23101ae42110f',
 '610612db87f08c6bfe466693',
 '669ad35dd904fe5b61bc6bce',
 '5dce3ccc32ccbf0cd54263db',
 '5e40dd7981d99c3120fcabc5',
 '6604487bcefa53a1ccd4a684',
 '6696be83d1acdaafee806dae',
 '66bf4e9bb19d166a02bd33df',
 '657ca800404c8884226c8f42',
 '66a9bd3cd2bad540c92fa09b',
 '66c36776e3beab6f29dda532',
 '5f0e0f586b19351132514f4d',
 '647648baa82fb44bb109f367',
 '65b889d01c19b76b2193ef2c',
 '6670c1485b46b4a1a09e968b',
 '6697f5e1583532661f6ffda3',
 '611187524a73e23c89d80e45',
 '6109d15f510e56947f3f1bae',
 '66b7aca57d8317c2a800416a',
 '66bb9c7f501107c4829068b9',
 '6109bfed18d1889e20fd6e99',
 '66d6fceb4cdf401e424d350d',
 '614ca018863895a0b6724719',
 '5d37d2861566530016a061de',
 '667c97204e10b9f328366df5',
 '5e911cfaefd95445d5a6c890',
 '6630fcae418bde6a9e7c3b47',
 '666b3c8c54ce3b910754cb8d',
 '66d7e7699bed3bb5177b5ea6',
 '669878eb97d1dc6253b65ac9',
 '663205b8ce17197f8d60bd27',
 '666496f6351ff47dfbb9f2e8',
 '5e9f877ee0b0960f3d2b6d30',
 '66c80d906de65f5b8f039d53',
 '663cb44c22c4bc48fa5773f7',
 '63026053812fe400f2929701',
 '66c164257fab16961369cc02',
 '66cfc142794197d72a9123fb',
 '66849ebd4dd65cfd282d2ad5',
 '5f0173db036ba22c01375033',
 '6560b73479ea077341c338a6',
 '5aeb9cdeaa05510001ff624e',
 '660154e5f99cf082f77a591f',
 '667af5cc382d3037050e3632',
 '5f8cbc5c355ea745e6cef2ca',
 '6634fcc04fdb39573179fb61',
 '663176c4d9c9b4d919f7b79e',
 '60fd051b45461e8b70752e25',
 '66bc0060af484cc27d44dd0e',
 '61010178ee16498e9a84233b',
 '65f7300049034aba6be17270',
 '66ae5b1cd75a435ad027e982',
 '6660977a350481fcb13e7f2d',
 '5f099b19d936ab01cbcde559',
 '66d9079509d725d2371f77b7',
 '5f06e8146c99472609ebcf8a',
 '6630ebf757488b8ef1f60642',
 '66087779533f1a209a98e0d8',
 '5c35101dbef9a20001e323f2',
 '6606e93fbb8cbe12379ec72e',
 '5ed73d9f9d89251b74a41130',
 '5ca51f05a15cb1001609491f',
 '63d1fc3f9823ab50782dfaf6',
 '654b9e831d0ebc88eb160a82',
 '66a44b2a8d7ed46a13a4b99c',
 '65cf6d7853481e8eca326136',
 '669bc59f4198ea65c9d8ef59',
 '664a145511338d9b7165824c',
 '62ac8793de53f30f2872e967',
 '663ab1fe2e8fa32717be4d67',
 '65bdaa4842494ba9f82fac54',
 '663c71465b4ca56a0ed95534',
 '61115178c8a4bbd5832f32ba',
 '65330c348f7089b3bd87236b',
 '66b126976a72a6a6ec4a23fc',
 '5deacc35443d0b1fe86a4f32',
 '668f8d7343028ae0faa7a907',
 '6647c91eef4f93024fafcf60',
 '5e76ea63f62c6925b6afe078',
 '61144f2e1dc689737c8d9bb1',
 '65845dda978052080941c93a',
 '65dfbfcbf70fbc2abebd92b9',
 '656c1adbdb298e7230d7b396',
 '65394a1487ee7f89125a1c67',
 '5c64189eede39b0001c39e61',
 '60b701050e43940c5101e929',
 '6668d35f652e2b8e0616538b',
 '66b26f90420305a3ef67ee54',
 '667a56fe23bc5cee5bdb18ad',
 '5fe76396a4feb05bf1629a6c',
 '65ba5335c9a29391ca7a88a1',
 '66509368fe4687505359b8d9',
 '5ed3fdbdb6ee6f39f590e455',
 '60cffac73993c4347f897f1a',
 '5d2f7fb4bb27200019010768',
 '66102810a75b88690a6a4316',
 '608a0175caaa968e48ae4b6d',
 '61213ec8d4bf50e3c08cbc0d',
 '66b435f9bf17321938e1595a',
 '664cf6d78f53d4a917230e0c',
 '5a4a94fef7b7bc00014e1462',
 '6647b851686419f12c0894c5',
 '662ad9c7673f1b65868e47de',
 '6542923cf0793b2a3dc55d69',
 '66bb6c9f70a35674f503bbc1',
 '654a54a0abb1fef304f60889',
 '65cd252065e6e71ce098fad0',
 '664e04ba5def4b939f39639f',
 '668d32274206c26e679bf65f',
 '6088df65082079cf2fdaa75a',
 '6101ea2ab4b86beb9f2bff48',
 '60e7639e8eca5490df1e412e',
 '650948d2e866e9c50c672d7a',
 '65493261b5e0320d0bfccd34',
 '62ac8d9f8d93291cb9d49d49',
 '6286b2b633eaea5194b9ba13',
 '5a6b580de6cc4a0001b6a06b',
 '652e8b28a8cbaf32300b45fd',
 '664c9f50386e6d97c7dd642f',
 '65fe2f14b03790cc470f5c06',
 '669c72a8f8a31bf01a09e2d7',
 '6667426fe3e924c0d17f0020',
 '6693f914675c6778f0a39f20',
 '66cc8edbd49e08c985d8e3fa',
 '614ece6fdaa50e12e6f3f98f',
 '66a2e7b7262f10fea744bff4',
 '660b1a5dd2c1a626cc817581',
 '65f9f19bd5507db6a31a9537',
 '63d475f2b52ddc6fbab9ce52',
 '663289a4557e849f0f0c4425',
 '66973a945551f2d54b344f7d',
 '5fbb4bf24594d6c5ad9df5cd',
 '5d41ee2257382300015d1560',
 '65c65bd00eb1fd6ec787d3c2',
 '66b547814ddd46987d3c02f4',
 '66d0edc6d856e2ee69dad939',
 '655da8fd266adbb32f5b0f24',
 '667d1a4033cc883ce431eda5',
 '62cdb6df9a4f07105bf66ee2',
 '666b3a54ad5b09a5dd2585c2',
 '65ee5dd9d4b632b7fb7a494c',
 '610341bbc7f7114aea9a2cea',
 '63bd81516745e78ee7f50f7f',
 '66d871da6bdc285c1140d4ec',
 '663aeabd3436216f0052e8ce',
 '608b7507b573e71c3708eec6',
 '669c11ea32c7511c9f84ec5e',
 '65366f1bc993d0465c14266f',
 '5e7d54301b20a23de6e1fb74',
 '665616bd2e3c013cde5789f5',
 '6500aa732c4f0eb077f8c809',
 '616b77ca71a5882a5c40cb2d',
 '60beb9301240ce01898b0675',
 '669879406aaa2c66de5c81ab',
 '610a1655e385fd7341e12778',
 '6632edd68127fba862de05bf',
 '665dd4c4f25dc25f070bd22b',
 '6109ca40ef8f38498af102ff',
 '61006ac5b3bd67e87ef4a9fc',
 '62a3b2b0eb528bfeb2ea2e02',
 '5b06d013732c5d000154dbf8',
 '66b27ae5b8cab7fc5a4856a4',
 '5d05aa4b28d214001d06bb93',
 '66467e9b63eb9f583aa6308d',
 '6595a67825c5829c491c8244',
 '66a95e3e62cb15f30191cde9',
 '66bbf2f451f0828ebf847823',
 '6635230c95f1d81114467933',
 '55883b5ffdf99b4021921cbc',
 '65f90cafdbdb392902db1918',
 '5cb60f1eefd4130001bbfdb7',
 '66734d3813db805ab4f055aa',
 '5d30cabd5124970019cb706c',
 '665b2c9da90bed8f64b91dbb',
 '6610bd91cd068c42215ee345',
 '663294f3abc8cbf9107f7510',
 '6632a45ac854ff55d9eb87e4',
 '6632d5306ee640b1e45f27ad',
 '6110e47224d01da919d5bb43',
 '653840dc6d810a55d78c9ee2',
 '66634b9fd11b27b999a3c56c',
 '65a31847f674ac3e98f0b3ba',
 '6323781f75962af097c34b5e',
 '66d90c2dff8698d23f051f36',
 '6659fd94e3e124a0920bc0ef',
 '6635005fc4f9cc4a9c84444d',
 '637e7734d78bd1f008b325c0',
 '6633a0e8efe1d018ea99bfc9',
 '5eddd48c9d8925ae26a88035',
 '64139842d720f2028a0e8fe2',
 '63784631952ef82ab4ee4db2',
 '6689648ac8d3a43fd880af96',
 '62b0985e7019ab81329bf57e',

In [63]:
donation_survey_data[donation_survey_data['PROLIFIC_PID']=='666dae8170b9b55c06c43019']

Empty DataFrame
Columns: [PROLIFIC_PID, document_id, task_id, task_category, timestamp, donation_data, attentionCheck, charityFeedbackPositive, charityFeedbackNegative, adSource, adSourceReason, recipeUsed, EA1, EA2, EA3, IA1, IA2, IA3, BI1, BI2]
Index: []

In [60]:
approval_1 = pd.read_csv('../data/stage2/participants_info/approval/prolific_export_66d8461863df672d5ffe15b2.csv')

In [61]:
final_people[final_people['Participant id'].isin(approval_1['Participant id'].tolist())]['Participant id'].tolist()

['66c4d2c2713b223511e4e676',
 '66aa59612e8897c5ab69032a',
 '66c7168869bba7cea5a4b4d2',
 '66656266d09c8744714c7b20',
 '66d1c54aefc822473cad25e0',
 '5e5291ff6c3d7d2a79ec869e',
 '5e648efca8c76520c918bb31',
 '603fcfc8b2061a10b80460e6',
 '5dc5bafe76244042b6b3b83f',
 '665e63b5ae7eaef8de21ab25',
 '66a79366e9d1eb8c901a2b23',
 '66d878851a20661f31eb775a',
 '59e833e72f63d30001c8fb86',
 '66413abd57f96e210a9cfe13',
 '5fb41bf3f84c7006ac8e30f2',
 '66299dc31130ad434839ad7d',
 '5dd38420a71de83809342ca3',
 '653fc86bca5191a208252115',
 '607778a26ff3de83125f50c5',
 '5ccafee43a7dbb0016546263',
 '611087db754dae727592763b',
 '66d7d7d2751da21eec22043b',
 '63d1477e452a9d7e822b79a8',
 '66d7d94ecf4c9082e82203be',
 '599ba05e05a0e30001f20344',
 '66d6afc8fc2d22bb7acdff2c',
 '65de422405a3595138be9b02',
 '65c1184408364a3a90a58786',
 '65ce19f79d8488ef10b52a3e',
 '6681c05c715c05de75f4ca0a',
 '6100c28ed43a1dea00f08633',
 '63eab79dbbee48659db0dcc4',
 '66d688b3b7b4aa17e073d128',
 '5fb2c8b4b04a8594fc0a3825',
 '66116efa868be6ac623de9fc',
 '66706191120230e6a89ddd0e',
 '66d7e189b4be3f503a2f230e',
 '66c63537c2829ac9fbbd9d5a',
 '66d8dccedad500ed9838cc6d',
 '66cb1eb8bf54a70914bbf1c8',
 '6655e61b775a076348a40b8d',
 '66bcbbd35d182838b25ff7df',
 '66359b64b4ef2e1f0830f5aa',
 '665e0790251ba96fa62b621c',
 '6629495997804a137f1cc8cb',
 '66b07f4e98d4f80738e8cc4d',
 '6697de4d08ef9922b2bc531a',
 '601750d7a0361e9a5e4fdc56',
 '6657368915008a8a9edc91a9',
 '6668c95f0adc056c9c178af2',
 '633c7424294f7a26710ca395',
 '66d7c1a21baad48e845dfdb0',
 '66240f705ac353a0bb928773',
 '629082739390703f993b12bd',
 '66ad6ef729911029f1357254',
 '5e07a94db7b33010fe2af9b4',
 '663c8bf2f8c29a144dc191de',
 '66d795e88a5d1559abbf5898',
 '63f7b8c25fc05973386fcdff',
 '631ff899c56260cb62016bca',
 '66d66b8e044e8ec3d8f4244e',
 '5d59d1c4f6a63300198681e8',
 '5f38e87099a44d40b79e5009',
 '66af3f96e50600f8f0da239a',
 '667ed5ce384ed14d7fddc226',
 '63ef5d25e9b2814388fe79d4',
 '66ba6496402d8157cdf92e7f',
 '5bc13b08f7ea0800019f91cd',
 '66d67902c511907836bec93b',
 '666f33fd54f65acc05b4c7b1',
 '665cea26beb2274c6c616503',
 '66c7e6e05a6d60e4278bfda7',
 '66633d2369f9da53edec1a9b',
 '65ea0eccf8677048425a4d2c',
 '55a35906fdf99b244bc18dc2',
 '62d38f10654f3fc8a393b551',
 '65f227fd72ee1b23f6640b5f',
 '65103482eef061cb1e3efb85',
 '66652ccee12aa31e8ff9fb38',
 '6113ff4bca90f6632e738e80',
 '60de1e91d169070d449d6c38',
 '66d1f88853da09348a20fbe8',
 '669ecc103e43370cd5ace699',
 '634f87d42fa897f3a8e3acad',
 '5c95970cd676900016e1a940',
 '5dc3552003f8562725a1b956',
 '62e3007fd78a0537dbe4fcbd',
 '5c2c62542c45d400014a32e6',
 '5c3b8e621ede2b00011604a9',
 '665531c847ff8f8d30f3425b',
 '653aac633ba278e5620ac9a9',
 '663bec51775d063f6fef7c82',
 '6019a44e01bf1810d777c4f8',
 '66c93b1e2e5675d92d52a64c',
 '6161e61324cc141a88e2d113',
 '66467574dad014b033fa664c',
 '5f879df674a3c81e20a40cd6',
 '66c5ea1ab6ff3306cd7b3bf6',
 '5ee3f2b74e35580dd5dc0925',
 '65f8e54f7d38e43856619feb',
 '5c78b032419dcc0014119082',
 '569b1e1aaf9ad7000d640f24',
 '6291293b4da216ae257c1867',
 '669519293719d01c2fdd1311',
 '661571d6cc16ee34676734df',
 '66a40d5dbd4e4f462556a4b1',
 '6650e04237e2aa9bd22fbfa4',
 '5cb1cd86637a05000187532b',
 '64485d7e807fdd8adea9db1d',
 '6672f62271d76001fb79f37c',
 '64eede50d732cf4ab3e590ad',
 '66c15c3ed1ed55387c5e03ef',
 '665f1309c64c2a4f4ea7bb91',
 '65e8d07f6dee8323f49a2b5b',
 '61282ca83be28773ac7c421f',
 '61118b5fd788969295997051',
 '5c054e8a553fb800011917d7',
 '66106c77782f1ef90fde89fa',
 '66d76a563b4869285ea98eea',
 '60fddd1ef83cc16b0411a2ba',
 '5a87b173b093f80001a7ece9',
 '643abe2183fc66157d8b0b9c',
 '5e120ac3ac9e168a3f6ded71',
 '63951be9d0b111f5fbab5eba',
 '5ec17a2e02be030625eaff6e',
 '60b9af795939f976cb74232a',
 '65cd1e75829ba4e3af71c2e5',
 '59ab51535e7f4800010eeed9',
 '62d5614f8e0bad3405c9dac9',
 '63e56678a87f209e2ca83059',
 '6632ba81acfa4541302b92d3',
 '60e7858c8bb1e77a5eee77de',
 '66577b8c804307020201a131',
 '5e7b815adb5aba05af6e6cc7',
 '5adc104b09eae2000112bd76',
 '61bb3a4f40db417c1a138ff4',
 '6339d15f5c1c670b3075f0fc',
 '5955a3eb98c9c400019f5c5f',
 '5c9a7872e2a8d00001585513',
 '5bd47734506cd3000101d181',
 '608f2aa883599160c8b87a79',
 '65cd5718a085f2323aad42de',
 '663294a9baf0036a40ac21a1',
 '66465a9ce1c681c9cbb78eca',
 '5f51404f39052135153b52b9',
 '5eb6f666c792cd6143878d27',
 '65464b7e526b25cfc1dfeeb2',
 '6298fbc8e35ae6800ccb3128',
 '65d50e7a510f38650aa5340c',
 '66815b1c397783d282513fb3',
 '6312c4daeb7e0f890b0b6a7f',
 '6340b7955ab968e4426eb476',
 '655cc974613aec120f21293b',
 '663a5fa6c0dd77f659a12550',
 '66c35f5caa40f6de28800d89',
 '665fe1a6172b55ef78d5256d',
 '5f836dbde582bf4f666b121e',
 '63f049c2d78b2bc822a16dac',
 '610e0dc76d43ecb6fea93855',
 '5f49f3262a3d07563d14a7f1',
 '5ee642c9f5cb343a58b1ef13',
 '5c7160b5b2516100015dfef1',
 '5c4e31b37065de00011f795d',
 '571c631fe1d2ec0013a68515',
 '62c65cd877b056c782d09fe1',
 '62e0326dbbda328df3ceade2',
 '667b2f1ebd0fe96b4afb83f5',
 '62349f9ac56251496a619264',
 '664c4e829445321c23a8de52',
 '669864e93f0ed6ee2a5d5cf8',
 '5e8fc5254447f82b9defc6b6',
 '66beefb9ec97ba13af1e64a8',
 '661e47e87d86f5629af43921',
 '665a433b5cf2b3fc75ec044e',
 '647b7636ede61061e7e37f70',
 '63bb98852cdc67dece8adb8e',
 '65b6dc6d9d685626cfef6857',
 '5dd1df8fb48da3240ca85c45',
 '6670b79e8456b0e5b1799c2f',
 '558cdd7efdf99b0f1cc5f4c1',
 '5e29c3e725dcfd01cef9f474',
 '63d98dcfa03c130e4599a907',
 '66293ab31f96fbbb4de50cb8',
 '66d8a09ce863659174f128cb',
 '66baaf7d1605ec806a07dc95',
 '65ca661975a7293b28a6efab',
 '5e1a7114a90da52e206de7ea',
 '66528148e922e522ab6fb4a9',
 '603ee4c2bd61ee1a08fd6a8a',
 '5ef42ba59401801d9f859e2d',
 '66439df8cecf5fd276606155',
 '6417dfab27377aff2c54af66',
 '6646728bbfb8084f4f45c0a7',
 '669c1bc6a24652548784f3fc',
 '5e48d3d8b26b05361ff522f2',
 '66d7259966407c81ec7fa46b',
 '6391a4d41c7025c8ad3d3e18',
 '66a2bc32533a358316cb9011',
 '61122e429887afaa2d131b09',
 '6535a4e5ea3f8466589b9aa0',
 '668cbad24e74402459631c48',
 '62da4563028fbcadf46412bc',
 '640415971520c41606ca4389',
 '665f9b37bc3065fed261e81c',
 '63f38cea3d56eac0c02a6eeb',
 '5b4eed90995d4e00010949b7',
 '63f2261685a2effaa7a16de6',
 '5c7cc4d59f29bd0018349603',
 '5a0c63e15d06850001affd96',
 '66c42da12cca15dd8d446e9a',
 '6664e5e07f6c9e89bdf50390',
 '6629b763d3f3a403d4a694d5',
 '66d3482fd505014e8eb8f424',
 '62e9c91168f8d1ff048964e9',
 '6569f997c88032b4981a222b',
 '56fb454534a0d300061a5070',
 '66d8b618dfe68065d1aa4a90',
 '65da7c7c8f8bac48599b274a',
 '559ea6e7fdf99b0fff2bda68',
 '600473adcef0ed5bbd905567',
 '60ba2ffd080107de026041d3',
 '665e2af7cff6620a57b2fd1c',
 '65a6b92c9a480cc6d7033b24',
 '5e405a1cfce14d29997364da',
 '6645ef6d923500eddcdc83ad',
 '5ef9302c07b0e310918662c3',
 '66277673bef725be86e38ffe',
 '66a684aaffcd837b0903b577',
 '66d916af0cf8c145a0aa3220',
 '62a0294e78bac60d6f9c49df',
 '63cc5fddd5813c609d5b28d5',
 '66a550e404332e1b17dddaaa',
 '665bc39f3d681ec2ea290e4d',
 '614e6f4f00a9e94b123316d3',
 '66c819bf71a1c4f4c2e729ef',
 '66aa791b9241ed81569fdd81',
 '669ea85495cd550e1bf25229',
 '66979a6297fc39c552df1e50',
 '66ae0709d8dd8981a2d6ee04',
 '5e7072e5fb136c63e94f3fa4',
 '65cbda4ad8076d79e5fd763f',
 '53c04378fdf99b360e022d92',
 '6044051ef235ef46052ab305',
 '6543ae61df4c68a0e486942f',
 '636148a83d7a7c349bb08436',
 '663f6499a07afa04b277d7e2',
 '658ea5a4017996f2dc550d43',
 '665bbd41a94b64c42a276e1d',
 '61074ae762b0186a302f1028',
 '606e3ddf19540080228e3a0c',
 '66a43f5957b881066dfeb5f1',
 '5fa04f87861aca05fab63ece',
 '628f0d7e3055b5d1887916c5',
 '6465cd750298e0714b6391cf',
 '66cce12cdb6f0ccdfdf668f3',
 '6644f37947ff3c7c3f9bbca1',
 '611343cebd1f50c6a0eaaf8c',
 '66d35d240ba45109a3882554',
 '5e45477286e27102354a420b',
 '6163d3ea0d13c617bb46c99b',
 '66bc94bf776a4169d4b15b7c',
 '660aecfcef9da76dd04ce2b1',
 '5b9ee4918d042e0001403143',
 '5e4044797946592823cbec2a',
 '570bc1ffb9b52b00102db939',
 '65626cc8ce1eab7aaec3a55b',
 '655fa55ae220887674baf9d6',
 '6690119d84f6b9351feaa95d',
 '6643a14a5f8e3396daaf127b',
 '66c3e65e4204580dbb03c32f',
 '66d66592ecdb6fe3de954329',
 '5661bce973ac87001180413a',
 '5e8601d90126b207e8c7a2aa',
 '66d34b99f621a0e7de30c1c4',
 '5e7a258b1a7e1c069379711c',
 '66d5a7788efaeec1102dcca5',
 '669284a314b1e3282fce4afd',
 '66d5f10ce1fa44997a861736',
 '6138af26127651134a88842c',
 '66847b3e4dd65cfd282d2305',
 '662687fc152ffe3df23453e4',
 '66659e3342b581f199e47a4d',
 '65a2aeeaff22f2a843564a85',
 '6647be4e1c230cad2c31613f',
 '66a4b815bba4dad1e16b497d',
 '665a66d17224187f00fca42c',
 '65d0d9fb04480131348a4672',
 '64776e3beba1085215214ec0',
 '5c0f500787e876000151fc5f',
 '60a2a8570a0f9cc00d6b9d1a',
 '65f1b56d620b27328a8836e8',
 '56e019f1a3b147000bc63028',
 '663de3332de392974f96decd',
 '663e4b5deaf50d8cef5ee1cb',
 '666794e38a2ac585e818ba17',
 '63caca07727ec41e89a42b72',
 '663fd4658572150cc2416c27',
 '6151fbe0c6b5a6b6af706100',
 '65cf6bcf11dca2196c5f9156',
 '5d2fb8f7034d7d000164bd18',
 '65e25f1b19693f423350b1ee',
 '661f4cfbeabfb4f58a8ecb4c',
 '63175042914da36ed2656593',
 '665a234c97c127c4605a9be1',
 '5e4566e8f64db704b739b757',
 '667085cc6ecfc9326ff6de72',
 '66293ce3dba0764775195e58',
 '66c6ad713afa83a1ba517d18',
 '56f9364e895094000c8f4967',
 '66a9979ad8c56c6f29446781',
 '66880bd9fc1509787faaa118',
 '5ea7514665002511e3b2da95',
 '6691a24cc9b007edebddc34c',
 '668564a45368836193b94269',
 '5ef32f0aeb0c9103d56a8558',
 '667a1f5e23bc5cee5bdb0a89',
 '6526c3297277ece1f3273549',
 '6674d66310b6684b86ddf7b9',
 '5e2926d80beb030ede110e67',
 '663922bf1ff7589784c76f51',
 '65cbe8940549c170484ea078',
 '667c3c4d32f4b404c46e325d',
 '66bed1da4f4333c83ef1e0ea',
 '5be728a4dbedc80001377337',
 '6643a328878e4f517c10de28',
 '5e32f34f2a574a01ebf984ab',
 '66aa97f1b6f7b6d542d37218',
 '65e150a2cca2780f6d77dfa6',
 '6679b6e51b2f51950f21fd65',
 '667d76240f5000a33e44bbaf',
 '5d7e777d0cc1c900195d5fbb',
 '666f57dffab7d1fcb56c8b53',
 '6680d577ce8b233327b0272e',
 '66cbc2627559d53c0e3e4ac4',
 '6695745ee6d6f8975139350a',
 '614f6bad672ef7cf5ecfd965',
 '66b2611ba705781f5401b996',
 '664cfd560115ff4b3f239bb8',
 '663bab395c5db0c5bc0944d3',
 '5cc3f0f9fdb33500018c5eeb',
 '66d6376eb15526056851d558',
 '66bb1bf162053ffd1926cc75',
 '63d1650b103325686e22e3b7',
 '5d250d243eea32001a079a3b',
 '63b6643cdbd50289e125a3e3',
 '5df3dcdd9b92b12b6db3a4e5',
 '665b7b047373d8da553237a6',
 '66b2eec417dcf3fb31ba0b45',
 '663ad3521b3d8f4931d80cd1',
 '66b4bb38f52cc2a093610c8d',
 '6657501de9a93ec1dae74cac',
 '66bcd07706e06c4d51e4885d',
 '668d6ef4c3b0ea4e2540622c',
 '66cc97280604bbb0c7bc71bd',
 '66c7adc45a77680b4053f8e2',
 '65374e5ad78177a9fe89f1a7',
 '63df06a8c5ac5f3c6bf77e6f',
 '60fd83ff5af11073b7d1ed62',
 '668f13e7da1b33ec8a028623',
 '62ec1fe3ebd392c343d85886',
 '66abbaa7e79344e4b77a7834',
 '55ea70c37480920010aa9982',
 '5d9f8573ce3daf0015e3e400',
 '66bba9777e53db38261e7a85',
 '60bc011503db109b7d46851d',
 '66b3ca6ea28f2b7430c73be1',
 '6656b41a68bc810ea64c442c',
 '668cb8f2ae575baf6cad3f36',
 '665f97db56096b743c2332b1',
 '5aeaa1192ef8f800014af05c',
 '5cb5e6927a92c500015c0de1',
 '66bcf6ae07e40789d4193872',
 '6693fdc21180149dc7f6619e',
 '5d5f31230fc94a001c632b69',
 '58adfc6e7cf56d0001f931a2',
 '66cd38eeecc9bb2fbf5a16e9',
 '608437f0b139060610c9f0c1',
 '663d6bcb7380775c879d17fd',
 '56baafe430d6b3000cf857ea',
 '651c4484ba17050f6b716614',
 '66857af993dcf9649eefd9f5',
 '66316ac602a513e2e74d5bdc',
 '5d951ede9b6f880018f63b6e',
 '66952fa8c27023759f09cd9e',
 '5aa83a71f6dfdd0001eb1690',
 '5bd612ce860b840001dc1a74',
 '664fc6ec0beb5400a141b77b',
 '661415341b1fdb1844c6f6a6',
 '66894dee33c97ad934460664',
 '66c0d9ef3c9b1d596446f813',
 '5c1ebf5f658e9200017ae7e9',
 '5d5338103c1b020018f36359',
 '65fb580ab7fbb2d518ee8eaa']

In [ ]:
{'65e18d62c5a884a634501922'}

In [ ]:
donation_survey_data

In [28]:
donation_survey_data[donation_survey_data['task_id']=='CONTROL_ENG']['document_id'].unique()

array(['4ff91bcf8009404cb25834c5_CONTROL'], dtype=object)

In [25]:
left_over_ids = donation_survey_data[donation_survey_data['task_category']=='ENG']['document_id'].value_counts().reset_index()
left_over_ids[left_over_ids['count'] < 5]

                 document_id  count
80  66c5a3e386c57a87db6f59f9      4

In [136]:
donation_survey_data

,PROLIFIC_PID,document_id,task_id,task_category,timestamp,donation_data,attentionCheck,charityFeedbackPositive,charityFeedbackNegative,adSource,adSourceReason,recipeUsed,EA1,EA2,EA3,IA1,IA2,IA3,BI1,BI2
0,607778a26ff3de83125f50c5,66c5a13c86c57a87db6f59d9,ENG,ENG,{'$date': '2024-09-04T18:46:18.789Z'},0.0,WWF,NaN,NaN,AS1,It seems generic.,['RU2'],1,1,1,4,3,3,2,2
1,548491acfdf99b0379939cc0,66c5a13c86c57a87db6f59d9,ENG,ENG,{'$date': '2024-09-04T22:44:43.452Z'},0.0,WWF,It gave information on what the organization h...,NaN,AS1,The use of exclamation points and generic writ...,"['RU1', 'RU3', 'RU5', 'RU6']",4,5,4,4,5,5,4,3
2,62d38f10654f3fc8a393b551,66c5a13c86c57a87db6f59d9,ENG,ENG,{'$date': '2024-09-04T22:48:37.138Z'},0.0,WWF,NaN,They didn't say how much of my donation would ...,AS1,It sounded very cut and dry. Basic,['RU7'],3,3,3,4,4,4,1,1
3,5e120ac3ac9e168a3f6ded71,66c5a13c86c57a87db6f59d9,ENG,ENG,{'$date': '2024-09-04T23:14:02.375Z'},1.0,WWF,The fact that a donation has an impact.,NaN,AS2,It sounds like a human wrote it with passion.,"['RU3', 'RU6']",4,4,4,4,4,4,4,3
4,65da7c7c8f8bac48599b274a,66c5a13c86c57a87db6f59d9,ENG,ENG,{'$date': '2024-09-05T10:40:24.928Z'},1.5,WWF,I liked how the advertisement made me feel par...,NaN,AS2,"While reading this advertisement, it felt like...","['RU1', 'RU3', 'RU5', 'RU6']",5,5,5,5,5,5,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,6654d2a81ff59c89050c1b01,95334737950147229a304e3d_LLM,ESP_LLM,ESP,{'$date': '2024-09-04T23:24:45.102Z'},0.7,WWF,Pueden agregar los años que tienen ayudando la...,NaN,AS1,El mensaje proyecta empatía y llamado a la acc...,"['RU1', 'RU5', 'RU3']",4,4,5,4,5,4,4,4
705,6560b73479ea077341c338a6,95334737950147229a304e3d_LLM,ESP_LLM,ESP,{'$date': '2024-09-05T01:05:56.432Z'},1.3,WWF,NaN,NaN,AS2,Por la manera en la que la information esta es...,"['RU6', 'RU5']",4,4,4,4,4,4,4,3
706,6668d35f652e2b8e0616538b,95334737950147229a304e3d_LLM,ESP_LLM,ESP,{'$date': '2024-09-05T06:04:35.308Z'},0.0,WWF,Abre Los Los Joana la situacion del WWF,N/a,AS1,Se siente como si fuera hecho en AI porque le ...,"['RU1', 'RU4']",4,5,4,4,4,4,4,3
707,63bd81516745e78ee7f50f7f,95334737950147229a304e3d_LLM,ESP_LLM,ESP,{'$date': '2024-09-05T21:58:04.137Z'},0.5,WWF,tiene informacion vital de la organizacion WWF.,NaN,AS2,"Asumo que fue escrito por un humano, pero no e...",['RU5'],4,4,4,4,4,4,3,4
708,6632d5306ee640b1e45f27ad,95334737950147229a304e3d_LLM,ESP_LLM,ESP,{'$date': '2024-09-06T21:32:11.323Z'},1.5,WWF,El impacto que mi contribucion puede tener.,Me gustaria ver ejemplos de el impacto por can...,AS2,El tono suena mas personal.,['RU6'],5,5,5,4,5,5,4,4

In [108]:
dreturned_doc_id = donation_survey_data[donation_survey_data['PROLIFIC_PID'].isin(returned_pid)]['document_id'].tolist()

In [109]:
inserted_docs[inserted_docs['_id'].isin(dreturned_doc_id)]

,_id,task_id,content,task_category,view_count
7,66c522869236da2225cc8cf2,ENG,**Help Children in Need with Every Bite!**Are ...,ENG,5
26,66c7a655f837defabd5eb872,ENG_1,"The climate, trees and plants can't speak up f...",ENG,5
59,66c6ef3c6db9c208f260cadb,ENG_2,Imagine a world in which mankind and nature co...,ENG,4
67,66c6fd416db9c208f260cb05,ESP_1,Me encanto recordar una vez que un niño de mi ...,ESP,5
74,66c75a3c6db9c208f260cc38,ENG_2,**Stand with WWF to Protect Our Planet!**\n\nA...,ENG,5
128,4ff91bcf8009404cb25834c5_CONTROL,CONTROL_ENG,The mission of World Wildlife Fund is to conse...,ENG,4

In [110]:
still_to_be_decreased = ['66c522869236da2225cc8cf2','66c7a655f837defabd5eb872','66c6fd416db9c208f260cb05','66c75a3c6db9c208f260cc38']

In [135]:
valid_list_participant_info['Status'].value_counts()

Status
AWAITING REVIEW    706
RETURNED             3
Name: count, dtype: int64

In [89]:
donation_survey_data.shape

(694, 20)

In [90]:
valid_list_participant_info.shape

(694, 20)

In [92]:
returne_cases = valid_list_participant_info[valid_list_participant_info['Status']=='RETURNED']

In [93]:
returne_cases

,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
415,66d8e2f83be2370ad4c59c73,60ff4947f329136761a45103,RETURNED,Not Applicable,2024-09-04T22:45:58.614000Z,2024-09-04T22:56:03.389000Z,NaN,2024-09-04T22:57:19.809000Z,NaN,C1MGNTBM,278,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
432,66d9c6a91a7276977de3d2cb,61549a2caa92d84f392000e9,RETURNED,Not Applicable,2024-09-05T14:56:47.593000Z,2024-09-05T14:59:55.221000Z,NaN,2024-09-05T14:59:56.526000Z,NaN,C1MGNTBM,3387,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
435,66da0e5fe31969071153701f,627ac8ebd1a87f7ea43604e7,RETURNED,Not Applicable,2024-09-05T20:02:43.408000Z,2024-09-05T20:09:43.100000Z,NaN,2024-09-05T20:09:43.714000Z,NaN,C1MGNTBM,356,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED

In [94]:
donation_survey_data[donation_survey_data['PROLIFIC_PID'].isin(returne_cases['Participant id'].tolist())]

,PROLIFIC_PID,document_id,task_id,task_category,timestamp,donation_data,attentionCheck,charityFeedbackPositive,charityFeedbackNegative,adSource,adSourceReason,recipeUsed,EA1,EA2,EA3,IA1,IA2,IA3,BI1,BI2
52,60ff4947f329136761a45103,66c522869236da2225cc8cf2,ENG,ENG,{'$date': '2024-09-04T22:56:00.452Z'},0.5,WWF,"I love the idea of helping things in need, whe...",NaN,AS2,"There’s a lot of passion in the ad, I don’t th...",['RU5'],4,5,5,5,5,5,5,4
213,61549a2caa92d84f392000e9,66c6ef3c6db9c208f260cadb,ENG_2,ENG,{'$date': '2024-09-05T14:59:43.571Z'},0.5,WWF,nice,NaN,AS1,nice,['RU4'],4,3,4,3,3,4,3,4
538,627ac8ebd1a87f7ea43604e7,4ff91bcf8009404cb25834c5_CONTROL,CONTROL_ENG,ENG,{'$date': '2024-09-05T20:09:40.238Z'},0.7,WWF,I liked that they are working to better the ea...,I didn't like that it did not provide specific...,AS1,It sounds whitewashed.,['RU7'],4,4,4,4,4,4,2,2